#!/bin/sh
set -e

if [ ! -L "/etc/xcollector" ]
then
  ln -s /usr/local/xcollector/conf /etc/xcollector
fi

if [ ! -L "/usr/local/xcollector/collectors/0/grok_nginx.py" ]
then
  ln -s /usr/local/xcollector/grok_scraper.py /usr/local/xcollector/collectors/0/grok_nginx.py
fi

if [ ! -L "/usr/local/xcollector/collectors/0/grok_tomcat.py" ]
then
  ln -s /usr/local/xcollector/grok_scraper.py /usr/local/xcollector/collectors/0/grok_tomcat.py
fi

if [ ! -d "/var/run/xcollector" ]
then
  mkdir -p "/var/run/xcollector"
fi

if [ ! -d "/var/log/xcollector" ]
then
  mkdir -p "/var/log/xcollector"
fi

case "$1" in
  configure)
	XCOLLECTOR_USER="xcollector"
	XCOLLECTOR_GROUP="xcollector"
    if [ -z "$(getent group $XCOLLECTOR_GROUP)" ]; then
	    addgroup --system "$XCOLLECTOR_GROUP" --quiet
    else
        echo "Group [$XCOLLECTOR_GROUP] already exists"
	fi
    if [ -z "$(id $XCOLLECTOR_USER)" ]; then
	    adduser --system --home /usr/local/xcollector --no-create-home \
		--ingroup "$XCOLLECTOR_GROUP" --disabled-password --shell /bin/false \
		"$XCOLLECTOR_USER"
    else
        echo "User [$XCOLLECTOR_USER] already exists"
	fi

  chown -R $XCOLLECTOR_USER.$XCOLLECTOR_GROUP /usr/local/xcollector
  chown -R $XCOLLECTOR_USER.$XCOLLECTOR_GROUP /var/run/xcollector
  chown -R $XCOLLECTOR_USER.$XCOLLECTOR_GROUP /var/log/xcollector
  ;;
esac


if [ -e "/etc/init.d/xcollector" ]; then
	update-rc.d xcollector defaults 95 10 >/dev/null
fi

